# Generated by Django 4.2.16 on 2024-09-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_images_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='photo',
        ),
    ]
