# Generated by Django 4.2.16 on 2024-10-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'ordering': ['-title']},
        ),
        migrations.AlterField(
            model_name='topic_relations',
            name='club_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clubs'),
        ),
        migrations.AlterField(
            model_name='topic_relations',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topics'),
        ),
    ]
