# Generated by Django 4.2.16 on 2024-10-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_teacher_teacherrelations_alter_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
    ]
