# Generated by Django 4.2.16 on 2024-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
