# Generated by Django 4.2.16 on 2024-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrelations',
            name='tuval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
