# Generated by Django 4.2.16 on 2024-10-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_teacherrelations_tuval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
    ]
