# Generated by Django 4.2.16 on 2024-10-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
