# Generated by Django 4.2.16 on 2024-10-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_class_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={'permissions': [('view_club', 'Can view club details'), ('manage_club', 'Can manage club details'), ('manage_club_design', 'Can edit club design'), ('manage_club_articles', 'Can manage articles for the club')]},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'ordering': ['-title'], 'permissions': [('view_class', 'Can view class'), ('manage_class', 'Can manage class details'), ('manage_registrations', 'Can manage class registrations'), ('assign_teacher', 'Can assign teacher to class')]},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('manage_teacher', 'Can add, edit, or remove teachers'), ('assign_classes', 'Can assign classes to teachers')]},
        ),
    ]
