"""
app models the container application db
here we have the existing urls (users/sites)
inside the app there are individual models that could be attached for each club
"""

from typing import Dict, List
from unittest.util import _MAX_LENGTH
from xml.parsers.expat import model
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import get_object_or_404
from django.utils import timezone
import uuid

class BaseModel(models.Model):
    """
    a base model to serve as a template for a table in the app.
    Base model columns: 
        ID(UUID-unique autoGenerated),
        created_by(USER-ID)
        created_by(datetime-autoGenerated)
        last_updated(datetime-last updated)
        description(TextField- notRequired)
    """
    
    ID = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        abstract = True

class Images(BaseModel):
    """
    Represents an image in the system.
    
    Fields:
        image (ImageField): The image file itself.
        club (ForeignKey to Clubs): The club associated with the image.
        page (CharField): The page or section of the site where the image is used (e.g., 'Article', 'Home', etc.).
        description (TextField): A brief description or alt text for the image.
        uploaded_at (DateTimeField): The date and time when the image was uploaded.
    """
    
    image = models.ImageField(upload_to='images/', null=False, blank=False)
    club = models.ForeignKey('Clubs', on_delete=models.CASCADE, related_name='images')
    page = models.CharField(max_length=100)  # To indicate which part of the site uses this image
    name = models.CharField(max_length=100,null=True, blank=True)
   
    

    def get_images_for_page(club, page: str,name:str=None) -> List[str]:
        """
        Returns a list of image URLs or descriptions for a specific club and page.
    
        Args:
            club (Clubs): The club associated with the image(s).
            page (str): The page or section of the site where the image is used (e.g., 'Article', 'Home', etc.).
    
        Returns:
            List[str]: A list of image URLs or their descriptions if no URL is available.
        """
        if name is None:
            images = Images.objects.filter(club=club, page=page)
        else:
            images = Images.objects.filter(club=club, page=page,name=name)
        image_list = []

        for image in images:
            if image.image:
                image_list.append(image.image.url)
            else:
                image_list.append("No image available")  # Fallback if no image or description

    def __str__(self):
        return f"Image for {self.club.name} on {self.page} page"

class Topics(BaseModel):
    """
    Represents topics that can be associated with clubs.
    
    Fields:
        name (TextField): The name of the topic (must be unique).
    
    Methods:
        get_club_topics(club_id): Returns topics associated with a specific club.
        get_topic_clubs(topic_name): Returns clubs associated with a specific topic.
    """
    
    name = models.TextField(null=True, blank=True, unique=True)
    
    def get_club_topics(club_id):
        """
        Fetches all topics associated with a particular club.
        """
        return topic_relations.objects.filter(club_ID=club_id).values_list('topic', flat=True)

    def get_topic_clubs(topic_name):
        """
        Fetches all clubs associated with a particular topic.
        """
        return topic_relations.objects.filter(topic__name=topic_name)

    def __str__(self):
        return self.name


class Clubs(BaseModel):
    """
    Represents a club with various attributes.
    
    Fields:
        name (CharField): The name of the club.
        topic (ForeignKey to Topics): The associated topic for the club.
        location (CharField): The location of the club.
        web_name (CharField): The web address or URL-friendly name for the club.
        contact_email (EmailField): The email address for the club's contact.
        contact_phone (CharField): The phone number for the club's contact.
        contact_person (CharField): The name of the primary contact person for the club.
    """
    
    name = models.CharField(max_length=255, null=False, blank=False)
    topic = models.ForeignKey(Topics, on_delete=models.CASCADE, null=True, related_name='clubs')
    location = models.CharField(max_length=255, null=True, blank=True)
    web_name = models.CharField(max_length=100, unique=True, null=False, blank=False)
    
    # Contact Information
    contact_email = models.EmailField(null=True, blank=True)
    contact_phone = models.CharField(max_length=15, null=True, blank=True)  # Assuming international phone numbers
    contact_person = models.CharField(max_length=255, null=True, blank=True)
    
    def get_clubs():
        """
        Returns a dictionary where the key is the club name and the value is a dictionary containing the photo URL, description, and web_name of each club associated with this topic.
        """
        # Fetch all clubs associated with this topic using topic_relations
        topics = Topics.objects.all()
        sorted_clubs = {}
        for topic in topics:
            club_relations = topic_relations.objects.filter(topic=topic)
            clubs = {}
            for relation in club_relations:
                club = relation.club_ID  # Access the club from the relation
            
               # Fetch images from the Images table
                image = get_object_or_404(Images,club=club, page='home',name='logo')

                # Create a dictionary with image URL, description, and web_name for each club
                clubs[club.name] = {
                    'photo': image,  # Get the first image URL if available
                    'description': club.description,
                    'web_name': club.web_name
                }
            sorted_clubs[topic.name] = clubs
        return sorted_clubs

    def get_club(self):
        """
        Returns a dictionary containing club information including BaseModel fields.
        """
        image = get_object_or_404(Images,club=self.ID, page='home',name='logo')

        return {
            'ID': str(self.ID),
            'created_by': self.created_by.username if self.created_by else None,
            'created_at': self.created_at.date,
            'last_updated': self.last_updated,
            'description': self.description,
            'name': self.name,
            'topic': self.topic.name if self.topic else None,  # Get topic name
            'location': self.location,
            'photo': image,
            'web_name': self.web_name,
            'contact_email': self.contact_email,
            'contact_phone': self.contact_phone,
            'contact_person': self.contact_person,
        }

    def __str__(self):
        return f'{self.name}, a {self.topic} club'

class topic_relations(BaseModel):
    """
    Represents the relationship between topics and clubs.
    
    Fields:
        topic (ForeignKey to Topics): The topic associated with the club.
        club_ID (ForeignKey to Clubs): The club associated with the topic.
        
    Methods:
        get_club_topics(club_id): Returns all topics related to a given club.
        get_topic_clubs(topic_name): Returns all clubs related to a specific topic.
    """
    
    topic = models.ForeignKey(Topics, on_delete=models.CASCADE, null=True)
    club_ID = models.ForeignKey(Clubs, on_delete=models.CASCADE, null=True)

    @staticmethod
    def get_club_topics(club_id):
        """
        Fetches all topics related to a specific club.
        """
        return topic_relations.objects.filter(club_ID=club_id).values_list('topic', flat=True)

    @staticmethod
    def get_topic_clubs(topic_name):
        """
        Fetches all clubs related to a specific topic.
        """
        return topic_relations.objects.filter(topic__name=topic_name)

    def __str__(self):
        return f'{self.club_ID} related to topic {self.topic}'
    


    
class Design(BaseModel):
    """
    Represents the design attributes for a club's webpage.
    
    Fields:
        club (ForeignKey to Clubs): The club that this design is associated with.
        color (CharField): The primary color used in the design.
        text (TextField): The primary text content or style information.
        font (CharField): The font style used in the webpage.
        background_image (ImageField): Background image for the webpage.
    """
    
    club = models.OneToOneField(Clubs, on_delete=models.CASCADE, related_name='design')
    color = models.CharField(max_length=7, default='#FFFFFF')  # Hex color value
    text = models.TextField(null=True, blank=True)
    font = models.CharField(max_length=100, null=True, blank=True)
    background_image = models.ImageField(upload_to='design_backgrounds/', null=True, blank=True)

    def edit_design(self, new_color=None, new_text=None, new_font=None, new_background_image=None):
        """
        Method to update the design attributes for a club's webpage.
        
        Args:
            new_color (str): New hex color code for the design.
            new_text (str): New text or style content.
            new_font (str): New font style for the webpage.
            new_background_image (ImageField): New background image.
        """
        if new_color:
            self.color = new_color
        if new_text:
            self.text = new_text
        if new_font:
            self.font = new_font
        if new_background_image:
            self.background_image = new_background_image
        self.save()

    def __str__(self):
        return f'Design for {self.club.name}'
    
class Article(BaseModel):
    """
    Represents an article in the system.

    Fields:
        title (CharField): The title of the article.
        content (TextField): The body of the article.
        author (ForeignKey to User): The author who created the article.
        club (ForeignKey to Clubs): The club related to the article.
        published (BooleanField): Indicates if the article is published.
        publication_date (DateTimeField): The date and time the article was published.
        tags (CharField): A comma-separated list of tags for the article.
        images (ImageField): Images related to the article.
    """

    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='articles')
    club = models.ForeignKey('Clubs', on_delete=models.CASCADE, related_name='articles')
    published = models.BooleanField(default=False)
    publication_date = models.DateTimeField(null=True, blank=True)
    tags = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ['-publication_date']

    def __str__(self):
        return self.title